#[derive(Debug, PartialEq)]
pub enum Token<'a> {
    Paragraph(&'a str),
    Heading(i8),
    Html(&'a str),
    Code(&'a str),
    Blockquote(&'a str),
    ThematicBreak,
    List(&'a str),
    ListItem(&'a str),
    Definition((&'a str, &'a str)),
    Emphasis(&'a str),
    Strong(&'a str),
    InlineCode(&'a str),
    Break,
    Link((&'a str, &'a str)),
    Image((&'a str, &'a str)),
    LinkReference((&'a str, &'a str)),
    ImageReference((&'a str, &'a str)),
}
